FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Allow results of `dotnet restore` to be cached if there are no changes to dependencies.
COPY ./NuGet.config /app/
COPY ./ef-app_backend-dotnet-core.sln /app/
COPY  ./src/Eurofurence.App.Common/Eurofurence.App.Common.csproj /app/src/Eurofurence.App.Common/Eurofurence.App.Common.csproj
COPY  ./src/Eurofurence.App.Tools.CliToolBox/Eurofurence.App.Tools.CliToolBox.csproj /app/src/Eurofurence.App.Tools.CliToolBox/Eurofurence.App.Tools.CliToolBox.csproj
COPY  ./src/Eurofurence.App.Server.Services/Eurofurence.App.Server.Services.csproj /app/src/Eurofurence.App.Server.Services/Eurofurence.App.Server.Services.csproj
COPY  ./src/Eurofurence.App.Server.Web/Eurofurence.App.Server.Web.csproj /app/src/Eurofurence.App.Server.Web/Eurofurence.App.Server.Web.csproj
COPY  ./src/Eurofurence.App.Backoffice/Eurofurence.App.Backoffice.csproj /app/src/Eurofurence.App.Backoffice/Eurofurence.App.Backoffice.csproj
COPY  ./src/Eurofurence.App.Infrastructure.EntityFramework/Eurofurence.App.Infrastructure.EntityFramework.csproj /app/src/Eurofurence.App.Infrastructure.EntityFramework/Eurofurence.App.Infrastructure.EntityFramework.csproj
COPY  ./src/Eurofurence.App.Domain.Model/Eurofurence.App.Domain.Model.csproj /app/src/Eurofurence.App.Domain.Model/Eurofurence.App.Domain.Model.csproj
COPY ./test/Eurofurence.App.Server.Services.Tests/Eurofurence.App.Server.Services.Tests.csproj /app/test/Eurofurence.App.Server.Services.Tests/Eurofurence.App.Server.Services.Tests.csproj
COPY ./test/Eurofurence.App.Server.Web.Tests/Eurofurence.App.Server.Web.Tests.csproj /app/test/Eurofurence.App.Server.Web.Tests/Eurofurence.App.Server.Web.Tests.csproj
COPY ./test/Eurofurence.App.Tests.Common/Eurofurence.App.Tests.Common.csproj /app/test/Eurofurence.App.Tests.Common/Eurofurence.App.Tests.Common.csproj
RUN dotnet restore

COPY ./src/ /app/src/
COPY ./test/ /app/test/
RUN touch src/Eurofurence.App.Backoffice/wwwroot/appsettings.json \
	&& dotnet restore \
	&& dotnet build src/Eurofurence.App.Backoffice/Eurofurence.App.Backoffice.csproj --configuration Release \
	&& dotnet publish src/Eurofurence.App.Backoffice/Eurofurence.App.Backoffice.csproj --output "/app/backoffice" --configuration Release
ENTRYPOINT dotnet artifacts/Eurofurence.App.Backoffice.dll http://*:30002
EXPOSE 30002

FROM nginx:1.27
ENV BACKOFFICE_BASE_PATH=
COPY --from=build /app/backoffice/wwwroot/ /usr/share/nginx/html/
COPY ./docker/nginx/etc/ /etc/
COPY ./docker/nginx/docker-entrypoint.d/ /docker-entrypoint.d/
RUN openssl req -x509 -nodes -days 365 -subj "/C=DE/ST=HH/O=EF Development/CN=ef.example.com" -addext "subjectAltName=DNS:ef.example.com" -newkey rsa:2048 -keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt
