version: '3.1'
services:
  backend:
    image: ghcr.io/eurofurence/ef-app_backend-dotnet-core:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '30001:30001'
    volumes:
      - './appsettings.json:/app/appsettings.json'
      - './firebase.json:/app/firebase.json'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: docker.io/mariadb:latest
    environment:
      MARIADB_DATABASE: 'ef_backend'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: mariadb-admin ping -h 127.0.0.1 -u root
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 30
volumes:
  db:
