FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
COPY ./src/ /app/src/
COPY ./test/ /app/test/
COPY ./ef-app_backend-dotnet-core.sln /app/
COPY ./NuGet.config /app/
WORKDIR /app
RUN touch src/Eurofurence.App.Backoffice/wwwroot/appsettings.json \
	&& dotnet restore \
	&& dotnet build src/Eurofurence.App.Backoffice/Eurofurence.App.Backoffice.csproj --configuration Release \
	&& dotnet publish src/Eurofurence.App.Backoffice/Eurofurence.App.Backoffice.csproj --output "/app/backoffice" --configuration Release
ENTRYPOINT dotnet artifacts/Eurofurence.App.Backoffice.dll http://*:30002
EXPOSE 30002

FROM nginx:1.27
COPY --from=build /app/backoffice/wwwroot/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf
RUN openssl req -x509 -nodes -days 365 -subj "/C=DE/ST=HH/O=EF Development/CN=ef.example.com" -addext "subjectAltName=DNS:ef.example.com" -newkey rsa:2048 -keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt
