name: Build and run tests

on: [push]
env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install tools
        run: dotnet tool install --global dotnet-ef
      - name: Install dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --no-restore
      - name: Test with the dotnet CLI
        run: dotnet test --no-build
