name: Create and publish container image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  call_build-and-push-image_nightly:
    if: startsWith(github.ref, 'refs/heads/')
    permissions:
      contents: read
      packages: write
    uses: eurofurence/reg-workflows/.github/workflows/docker-build-push.yml@main
    with:
      image-name: ${{ github.repository }}
      image-tags: nightly
      full-repo-url: https://github.com/${{ github.repository }}
      branch-or-tag-name: ${{ github.ref_name }}
      commit-hash: ${{ github.sha }}
      registry-user: ${{ github.actor }}
    secrets:
      registry-pass: ${{ secrets.GITHUB_TOKEN }}

  call_build-and-push-image_release:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
    uses: eurofurence/reg-workflows/.github/workflows/docker-build-push.yml@main
    with:
      image-name: ${{ github.repository }}
      image-tags: ${{ github.ref_name }} latest
      full-repo-url: https://github.com/${{ github.repository }}
      branch-or-tag-name: ${{ github.ref_name }}
      commit-hash: ${{ github.sha }}
      registry-user: ${{ github.actor }}
    secrets:
      registry-pass: ${{ secrets.GITHUB_TOKEN }}
